"""Copies the CSS of components that are rendered *directly* (imported, not via the editor slot)
into the parent's styles.css, because ikas only scopes/collects a component's own styles.css
(and its sub-folder styles). Re-run after editing any of the source component styles:

    python scripts/sync-inlined-styles.py
"""
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent / "src"
BEGIN = "/* ===== BEGIN inlined child styles (generated by scripts/sync-inlined-styles.py) ===== */"
END = "/* ===== END inlined child styles ===== */"

TARGETS = {
    "components/ProductDetail/styles.css": [
        "components/ProductDetailNameFavorite",
        "components/ProductDetailPrices",
        "components/ProductDetailProductGroup",
        "components/ProductDetailBundleProduct",
        "components/ProductDetailVariant",
        "components/ProductDetailOptionSet",
        "components/ProductDetailAddToCart",
        "components/ProductDetailBackInStock",
        "components/ProductDetailOffer",
        "components/ProductDetailDescription",
        "components/CkProductAssurance",
    ],
    "sub-components/ProductCard/styles.css": [
        "components/CardProductName",
        "components/CardProductPrice",
    ],
}


def collect(folder: Path) -> str:
    parts = []
    for css in sorted(folder.rglob("styles.css")):
        parts.append(f"/* --- {css.relative_to(SRC).as_posix()} --- */\n" + css.read_text(encoding="utf-8").strip())
    return "\n\n".join(parts)


for target, sources in TARGETS.items():
    path = SRC / target
    text = path.read_text(encoding="utf-8")
    if BEGIN in text:
        text = text[: text.index(BEGIN)].rstrip() + "\n"
    block = "\n\n".join(collect(SRC / s) for s in sources)
    path.write_text(f"{text.rstrip()}\n\n{BEGIN}\n{block}\n{END}\n", encoding="utf-8")
    print(f"{target}: {len(block)} chars from {len(sources)} components")
